var platformer = {
    map : 
    '                                                                                                 uuuuuu                                                                                                                                                                                                     '+
    '                                                                                         uu       uuuu                                                                                                                                                                                                      '+
    '                                                                  uuuu                                                                                                                                                                                                                                      '+
    '                                                                   uu            uuuu                                                                                                                                                                                                                       '+
    '                                           dd                                     uu                                                                                                                                                                                                                        '+
    '                                          dxddd                           uu                                uuu                                                                                                                                                                                             '+
    '              x   x                      xxdddx                          uuuu                                                                                                                                                                                                                               '+
    '             xx   xx                    xxxdddxx                                                                                                                                                                                                                                                            '+
    '    q1      xxx   xxx                   xxxxddxxx                                                                                                                                                                                                                                                           '+
    '   q4      xxxx   xxxx                 xxxxxdxdxxx           x  x                                                                                                                                                                                                                                           '+
    '          xxxxx   xxxxxxx              xxxxxdxdxxx           x  x                                                                                                                                                                                                                                           '+
    '         xxxxxx   xxxxxxx              xxxxddxxdxx           x  x                                                      q2                                                                                                                                                                                   '+
    'xxxxxxxxxxxxxxx   xxxxxxx    xxxxxxx   xooddooooox  xxxxxxxxxxwwxdddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooddd>>ddddddddddddddddddddddddwwwwwwdddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'oooooooooooooox   xooooox    xooooox   xodooooooox  xoooooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox   xooddooooox  xooooooooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox   xoooodoodox  xooooooooooooooooooddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox   xooooddddox  xoooooooooooooooooooodddddooooddddddddddddddddddddddddddooooooooddddddddddddoooooooodddddddddddddddddddddddddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox   xoddddddoox  xoooooooooooooooooooooooooooooooddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox   xooooddooox  xoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox     oooxx  oo  xoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xooooox                xoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'oooooooooooooox   xooooox    xoooooooo              xoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'ooooooooooooooxdddxooooox--ddxoooooooooxxxxxxooxxxwwxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo '+
    'xxxxxxxxxxxxxxxdddxxxxxxx--ddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                  x                                                                                                                                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                        >>W       x                                                                                                                                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                  x                                                                                >>W                                                                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                  x                                                                                                                                                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                                                                              w<<                                                                                 W<<                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                                             W                                                                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                                                                 W                                                                                                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                 >>>>w                                                                                                                                                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                                                                                                                                                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                                                                                                                                                                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   uuuuuuuuu<<<<<x              >>>>>>>>wxx                                                                                                                                                                          w<<       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x       <           xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x      >u>          xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                  w<<                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x       <           xxxxxxxxxxxxxxx              xxxxxxxxxxx  x                                                                                                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                      >>w                                                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                               W<<                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx    x                          >                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx        x                                                        W                                                                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx           x                                                                                                                                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                 <<xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxx       uuuuuuuuuuuuuuuuuuuuuuuuuu<<xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                                                xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   x>>>>>uuuuuuuuu              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x >>                xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x                   xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x              x x  xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'x           x  x    xxxxxxxxxxxxxxx>            <xxxxxxxxxxx                                                                                                                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'x      x            xxxxxxxxxxxxxxxx>          <xxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'xxx                 xxxxxxxxxxxxxxxxx>        <xxxxxxxxxxxxx         x                                  x                                                                                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'xxx                 xxxxxxxxxxxxxxxxxx>      <xxxxxxxxxxxxxx         x                                  x                                                                                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'x              x x  xxxxxxxxxxxxxxxxxxx>    <xxxxxxxxxxxxxxx         x      o                           xx                   x                                                                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'x           x  x    xxxxxxxxxxxxxxxxxxxxWWWWxxxxxxxxxxxxxxxx         x      o                                                                                                                                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'x      x            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      o    ooooooooo                                                                                                                                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'xxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      ooo   o     o                                                                                                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+ 
    'xxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      o o   o     o                                                                                                                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'xxxxxxxxxxxxxxxxxxwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWWW>>>>>>ww>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>uuuuuuuuuuuuuuuuuuW<<<<<uuuuuuuuuuuu<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx '+
    'n',
    startX : 0,
    startY : 600,
    width : 300,
    height : 23,
    blockSize : 45,
}