var testMap = {
    map : 
    '                                                                   x                                                                                                                                                                            '+
    '                                                         >>W       x                                                                                                                                                                            '+
    '                                                                   x                                                                                >>W                                                                                         '+
    '                                                                   x                                                                                                                                                                            '+
    '                                                                                                                               w<<                                                                                 W<<                          '+
    '                                                                                              W                                                                                                                                                 '+
    '                                                                                                                  W                                                                                                                             '+
    '                                                                  >>>>w                                                                                                                                                                         '+
    '                                                     q1                                                                                                                                                                                         '+
    '                                                                                                                                                                                                                                                '+
    '                    uuuuuuuuu<<<<<x              >>>>>>>>wxx                                                                                                                                                                          w<<       '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '        <           xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '       >u>          xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                  w<<                                                               '+
    '        <           xxxxxxxxxxxxxxx              xxxxxxxxxxx  x                                                                                                                                                                                 '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                      >>w                                                                                           '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                               W<<                                                                  '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx    x                          >                                                                                                                                                    '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx        x                                                        W                                                                                                                  '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx           x                                                                                                                                                                        '+
    '                  <<xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxx       uuuuuuuuuuuuuuuuuuuuuuuuuu<<xxxxxxxxxxxxxxxxxxxxxxxx'+
    '                                                 xxxxxxxxxxx                                                                                                                                                                                    '+
    '                                                 xxxxxxxxxxx                                                                                                                                                                                    '+
    '                                                 xxxxxxxxxxx                                                                                                                                                                                    '+
    '                    x>>>>>uuuuuuuuu              xxxxxxxxxxx                                                                                                                                                                                    '+
    '  >>                xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '                    xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+
    '               x x  xxxxxxxxxxxxxxx              xxxxxxxxxxx                                                                                                                                                                                    '+ 
    '            x  x    xxxxxxxxxxxxxxx>            <xxxxxxxxxxx                                                                                                                                                                                    '+ 
    '       x            xxxxxxxxxxxxxxxx>          <xxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                       '+ 
    'xxx                 xxxxxxxxxxxxxxxxx>        <xxxxxxxxxxxxx         x                                  x                                                                                                                                       '+ 
    'xxx                 xxxxxxxxxxxxxxxxxx>      <xxxxxxxxxxxxxx         x                                  x                                                                                                                                       '+
    '               x x  xxxxxxxxxxxxxxxxxxx>    <xxxxxxxxxxxxxxx         x      o                           xx                   x                                                                                                                  '+ 
    '            x  x    xxxxxxxxxxxxxxxxxxxxwwwwxxxxxxxxxxxxxxxx         x      o                                       q2                                                                                                                          '+ 
    '       x            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      o    ooooooooo                                                                                                                                                      '+ 
    'xxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      ooo   o     o                                                                                                                                                       '+ 
    'xxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      o o   o     o                                                                                                                                                       '+
    'xxxxxxxxxxxxxxxxxxwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwww>>>>>>ww>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>uuuuuuuuuuuuuuuuuuW<<<<<uuuuuuuuuuuu<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'+
    'n',
    startX : 0,
    startY : 400,
    width : 240,
    height : 41,
    blockSize : 20,
}